version: '3.9'
services:
  mongodb:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    networks:
      - yolo-service
    volumes:
      - yolo-volumes:/etc/mongodb/data

  backend:
    image: velmagatwiri/yolo:v0.02
    ports: 
      - 5000:5000
    environment:
      PORT: 5000
      MONGODB_URI: mongodb://db_container:27017
      DB_NAME: yolomy
    depends_on: 
      - mongodb 
    networks:
      - yolo-service
  
  client:
    image: velmagatwiri/yolo-client:v0.02
    tty: true
    ports: 
      - 3000:3000
    environment:
      PORT: 3000
    depends_on:
      - backend
    networks:
      - yolo-service

networks:
  yolo-service:
    driver: bridge
volumes:
  yolo-volumes: