version: '3.9'
services:
  mongodb:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes: 
      - mongodb:/data/db

  backend:
    build: ./backend
    ports: 
      - 5000:5000
    environment:
      PORT: 5000
      MONGODB_URI: mongodb://db_container:27017
      DB_NAME: yolomy
    depends_on: 
      - mongodb 
  
  client:
    build: ./client
    tty: true
    ports: 
      - 3000:3000
    environment:
      PORT: 3000
    depends_on:
      - backend

volumes:
  mongodb: {}